import = [
  "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[env]
TERM="xterm-256color"

[font]
  normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
  size = 12

[window]
  padding = { x = 0, y = 0}
  dynamic_padding = true
  opacity = 0.8
